// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VasilevaAnnaKT_42_23.Database;

#nullable disable

namespace VasilevaAnnaKT_42_23.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20261006072127_Migr1")]
    partial class Migr1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.HasKey("DisciplineId")
                        .HasName("pk_tb_discipline_discipline_id");

                    b.ToTable("tb_discipline", (string)null);
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("discipline_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("GradeId")
                        .HasName("pk_tb_grade_grade_id");

                    b.HasIndex(new[] { "DisciplineId" }, "idx_tb_grade_fk_f_discipline_id");

                    b.HasIndex(new[] { "StudentId" }, "idx_tb_grade_fk_f_student_id");

                    b.ToTable("tb_grade", (string)null);
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("int")
                        .HasColumnName("course");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int")
                        .HasColumnName("speciality_id");

                    b.HasKey("GroupId")
                        .HasName("pk_tb_group_group_id");

                    b.HasIndex(new[] { "SpecialityId" }, "idx_tb_group_fk_f_speciality_id");

                    b.ToTable("tb_group", (string)null);
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Speciality", b =>
                {
                    b.Property<int>("SpecialityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("speciality_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialityId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar")
                        .HasColumnName("code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("title");

                    b.HasKey("SpecialityId")
                        .HasName("pk_tb_speciality_speciality_id");

                    b.ToTable("tb_speciality", (string)null);
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("first_name");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("last_name");

                    b.HasKey("StudentId")
                        .HasName("pk_tb_student_student_id");

                    b.HasIndex(new[] { "GroupId" }, "idx_tb_student_fk_f_group_id");

                    b.ToTable("tb_student", (string)null);
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Grade", b =>
                {
                    b.HasOne("VasilevaAnnaKT_42_23.Models.Discipline", "Discipline")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_f_discipline_id");

                    b.HasOne("VasilevaAnnaKT_42_23.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_student_id");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Group", b =>
                {
                    b.HasOne("VasilevaAnnaKT_42_23.Models.Speciality", "Speciality")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_f_speciality_id");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Student", b =>
                {
                    b.HasOne("VasilevaAnnaKT_42_23.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Discipline", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Speciality", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("VasilevaAnnaKT_42_23.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
